version: "3"
services:
  mini_blog:
    container_name: mini_blog
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mini_blog
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: